version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15
      
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-modules-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-modules-v2-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm test


